common: &common
  adapter: postgresql
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *common
  database: distinct_development

test:
  <<: *common
  database: distinct_test

production:
  <<: *common
  database: distinct_production